workflows:
  capacitor-ios-workflow:
    name: Capacitor iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install Cap iOS platform
        script: |
          sudo npm install -g @capacitor/cli
          npm install @capacitor/ios
          npx cap add ios || true
      - name: Capacitor Sync
        script: |
          npx cap sync
      - name: Build iOS App
        script: |
          cd ios/App
          pod install
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -sdk iphoneos -derivedDataPath build archive
    artifacts:
      - ios/App/build/Build/Products/Debug-iphoneos/*.app
      - ios/App/build/**/*.xcarchive